### ISSUE TITLE
Can't find aqua.jar

### ISSUE THREAD

**Issue by OriginalAshXD** [Soyandroid/aqua#1]
When I try running start.bat all it does is give me this (Error: Unable to access jarfile aqua.jar):

![Screenshot 2021-12-29 144430](https://user-images.githubusercontent.com/68449238/147698058-a51f2482-7d08-4d7f-a20b-cea553adff44.png)

**Comment by maihiang** [comment]
I have come across the same issue. How did you solve it?

**Comment by OriginalAshXD** [comment]
> I have come across the same issue. How did you solve it?

I forgot what I did then, but I did make a sort of manager for this reason 
https://github.com/RukaButOriginal/AllNet-Aqua-manager

**Comment by synthesia123** [comment]
> > I have come across the same issue. How did you solve it?
> 
> I forgot what I did then, but I did make a sort of manager for this reason https://github.com/RukaButOriginal/AllNet-Aqua-manager

a huge THANK YOU to you! I've been suffering from this issue for days, your version really solved it!
